<?php

return [
    'role_structure' => [
        'titan' => [
            'users' => 'b,c,r,u,d',
            'address' => 'b,c,r,u,d',
            'basic' => 'b,c,r,u,d',
            'benefit' => 'b,c,r,u,d',
            'contact' => 'b,c,r,u,d',
            'contract' => 'b,c,r,u,d',
            'convict' => 'b,c,r,u,d',
            'education' => 'b,c,r,u,d',
            'emergency' => 'b,c,r,u,d',
            'experience' => 'b,c,r,u,d',
            'family' => 'b,c,r,u,d',
            'medical' => 'b,c,r,u,d',
            'reference' => 'b,c,r,u,d',
            'skill' => 'b,c,r,u,d',
            'training' => 'b,c,r,u,d',

            'mAddress' => 'b,c,r,u,d',
            'mBlood' => 'b,c,r,u,d',
            'mCitizenship' => 'b,c,r,u,d',
            'mCivil' => 'b,c,r,u,d',
            'mCompany' => 'b,c,r,u,d',
            'mDepartment' => 'b,c,r,u,d',
            'mEducation' => 'b,c,r,u,d',
            'mStatus' => 'b,c,r,u,d',
            'mExtension' => 'b,c,r,u,d',
            'mFamily' => 'b,c,r,u,d',
            'mGender' => 'b,c,r,u,d',

        ],
        'admin' => [
            'users' => 'b,c,r,u,d',
            'address' => 'b,c,r,u,d',
            'basic' => 'b,c,r,u,d',
            'benefit' => 'b,c,r,u,d',
            'contact' => 'b,c,r,u,d',
            'contract' => 'b,c,r,u,d',
            'convict' => 'b,c,r,u,d',
            'education' => 'b,c,r,u,d',
            'emergency' => 'b,c,r,u,d',
            'experience' => 'b,c,r,u,d',
            'family' => 'b,c,r,u,d',
            'medical' => 'b,c,r,u,d',
            'reference' => 'b,c,r,u,d',
            'skill' => 'b,c,r,u,d',
            'training' => 'b,c,r,u,d',

            'mBlood' => 'b,c,r,u,d',
            'mCitizenship' => 'b,c,r,u,d',
            'mCivil' => 'b,c,r,u,d',
            'mCompany' => 'b,c,r,u,d',
            'mDepartment' => 'b,c,r,u,d',
            'mEducation' => 'b,c,r,u,d',
            'mStatus' => 'b,c,r,u,d',
            'mExtension' => 'b,c,r,u,d',
            'mFamily' => 'b,c,r,u,d',
        ],
        'human-resource' => [
            'users' => 'b,c,r,u',
            'address' => 'b,c,r,u,d',
            'basic' => 'b,c,r,u,d',
            'benefit' => 'b,c,r,u,d',
            'contact' => 'b,c,r,u,d',
            'contract' => 'b,c,r,u,d',
            'convict' => 'b,c,r,u,d',
            'education' => 'b,c,r,u,d',
            'emergency' => 'b,c,r,u,d',
            'experience' => 'b,c,r,u,d',
            'family' => 'b,c,r,u,d',
            'medical' => 'b,c,r,u,d',
            'reference' => 'b,c,r,u,d',
            'skill' => 'b,c,r,u,d',
            'training' => 'b,c,r,u,d',

            'mBlood' => 'b,c,u,',
            'mCitizenship' => 'b,c,u',
            'mCivil' => 'b,c,r,u',
            'mCompany' => 'b,c,r,u',
            'mDepartment' => 'b,c,r,u',
            'mEducation' => 'b,c,r,u',
            'mStatus' => 'b,c,r,u',
            'mExtension' => 'b,c,r,u',
            'mFamily' => 'b,c,r,u',
        ],
        'executive' => [
            'users' => 'b',
            'address' => 'b',
            'basic' => 'b',
            'benefit' => 'b','u',
            'contact' => 'b',
            'contract' => 'b',
            'convict' => 'b',
            'education' => 'b',
            'emergency' => 'b',
            'experience' => 'b',
            'family' => 'b',
            'medical' => 'b',
            'reference' => 'b',
            'skill' => 'b',
            'training' => 'b',
        ],
        'manager' => [
            'address' => 'b',
            'basic' => 'b',
            'benefit' => 'b',
            'contact' => 'b',
            'convict' => 'b',
            'education' => 'b',
            'emergency' => 'b',
            'experience' => 'b','u',
            'family' => 'b',
            'medical' => 'b',
            'reference' => 'b','u',
            'skill' => 'b',
            'training' => 'b','u',
        ],
        'supervisor' => [
            'address' => 'b',
            'basic' => 'b',
            'benefit' => 'b',
            'contact' => 'b',
            'convict' => 'b',
            'education' => 'b',
            'emergency' => 'b',
            'experience' => 'b','u',
            'family' => 'b',
            'medical' => 'b',
            'reference' => 'b','u',
            'skill' => 'b',
            'training' => 'b','u',
        ],
        'employee' => [
            'address' => 'b','u',
            'basic' => 'b','u',
            'benefit' => 'b','u',
            'contact' => 'b','u',
            'convict' => 'b','u',
            'education' => 'b','u',
            'emergency' => 'b','u',
            'experience' => 'b','u',
            'family' => 'b','u',
            'medical' => 'b','u',
            'reference' => 'b','u',
            'skill' => 'b','u',
            'training' => 'b','u',
        ],
    ],
    'permission_structure' => [],
    'permissions_map' => [
        'b' => 'browse',
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete'
    ]
];
